/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareEngineering;
import java.io.*;
import org.junit.*;
import static org.junit.Assert.*;
import java.sql.*;


public class AppTest {

    Connection con;
    ConnectionManager cm;
    
    public AppTest(){
        cm = ConnectionManager.getCM("academicsystemtest");
        con = cm.getConnection();
    }

    @Before
    public void setUp(){
        cm.runScript("../Sql_files/addDataTest.sql");
    }

    
    @Test public void testPersonClass() {
        Person person1 = new Person("");
        Person person2 = new Person("John");

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        assertEquals(person1.username, "");

        person1.manager();
        assertEquals("This is the manager method of the Person class", outContent.toString().trim());

        outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        assertEquals(person2.username, "John");
        person2.manager();
        assertEquals("This is the manager method of the Person class", outContent.toString().trim());
    }

    @Test public void handleAuthTest() throws Exception {
        String databaseName = "academicsystemtest";
        Person person = App.handleAuth("student1", "student1",databaseName);
        Person person1 = App.handleAuth("faculty1", "faculty1",databaseName);
        Person person2 = App.handleAuth("academic1", "academic1",databaseName);
        Person person3 = App.handleAuth("fake", "fake",databaseName);
        Person person4 = App.handleAuth("admin3","admin3",databaseName);

        assertEquals(person.role, "student");
        assertEquals(person1.role, "instructor");
        assertEquals(person2.role, "academic");
        assertEquals(person3, null);
        assertEquals(person4, null);
    }

    @Test public void mainTest1() throws Exception{
        String input = "student1\nstudent1\n7\n";
        ByteArrayInputStream inputStream = new ByteArrayInputStream(input.getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(outputStream);
        System.setOut(printStream);

        App.main(new String[]{"test"});

        String output = outputStream.toString();
        String expectedOutput = "Welcome, Student student1";
        assertTrue(output.contains(expectedOutput));
    }

    @Test public void mainTest2() throws Exception{
        String input = "student\nstudent\n-1\n";
        ByteArrayInputStream inputStream = new ByteArrayInputStream(input.getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(outputStream);
        System.setOut(printStream);

        App.main(null);

        String output = outputStream.toString();
        String expectedOutput = "Exiting...";
        assertTrue(output.contains(expectedOutput));
    }
}
