/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareEngineering;
import org.junit.Test;
import java.io.*;
import static org.junit.Assert.*;


public class AppTest {

    
    @Test public void testPersonClass() {
        Person person1 = new Person("");
        Person person2 = new Person("John");

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        assertEquals(person1.username, "");

        person1.manager();
        assertEquals("This is the manager method of the Person class", outContent.toString().trim());

        outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        assertEquals(person2.username, "John");
        person2.manager();
        assertEquals("This is the manager method of the Person class", outContent.toString().trim());
    }

    @Test public void handleAuthTest() throws Exception {
        Person person = App.handleAuth("admin", "admin");
        Person person1 = App.handleAuth("admin1", "admin1");
        Person person2 = App.handleAuth("admin2", "admin2");
        Person person3 = App.handleAuth("fake", "fake");
        Person person4 = App.handleAuth("admin3","admin3");

        assertEquals(person.role, "student");
        assertEquals(person1.role, "instructor");
        assertEquals(person2.role, "academic");
        assertEquals(person3, null);
        assertEquals(person4, null);
    }
}
